#!/bin/bash
# modified <x@xero.nu>

#f=▓;e=░
f=━
e=━

host=`hostname`
kernel=`uname -r`
bat=/sys/class/power_supply/BAT0

bar () {
  perc=$1; size=$2
  inc=$(( perc * size / 100 ))
  out=
  color1="36"
  color2="37"
  for v in `seq 0 $(( size - 1 ))`;do
  test "$v" -le "$inc" \
  && out="${out}\e[1;${color2}m${f}" || out="${out}\e[0;${color1}m${e}"
  done;printf $out
}
clear && printf "\e[3J\n"

cpu=`mpstat -u | awk '/all/' | cut -b 20-24`
c_lvl=`printf "%.0f" $cpu`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " cpu" "$c_lvl%" `bar $c_lvl 15`

ram=`free | awk '/Mem:/ {print int($3/$2 * 100.0)}'`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " ram" "$ram%" `bar $ram 15`

#spc=`df -h | awk '/dev\/mmc/ {print int($3/$2 * 100.0)}'`
spc=`df -h | awk '/dev\/mmcblk0p2/' | cut -b 35-36`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " /" `bar $spc 15`

bf=`cat $bat/charge_full`
bn=`cat $bat/charge_now`
charge=`printf $(( 100 * $bn / $bf ))`

case 1 in
  $(($charge <= 15)))
    color='31' ;;
  *)
    color='36' ;;
esac
printf "   \e[0;${color}m%-4s \e[1;${color}m%-5s %-25s " " bat" "$charge%" `bar $charge 15 $color`

temp=`sensors | awk '/Core\ 0/ {gsub(/\+/,"",$3); gsub(/\..+/,"",$3)    ; print $3}'`
case 1 in
  $(($temp <= 50)))
    color='34' ;;
  $(($temp >= 75)))
    color='31' ;;
  *)
    color='36' ;;
esac
printf "   \e[0;${color}m%-4s \e[1;${color}m%-5s %-25s \n\n" "$temp°c " `bar $temp 15 $color`

echo -e "\n      \e[36mROBCO INDUSTRIES UNIFIED OPERATING SYSTEM \n\
            COPYRIGHT 2075-2077 ROBCO INDUSTRIES \n\
                             -Server \e[33m$name\e[0m@\e[34m$host\e[36m-\e[0m\n\n"

