#!/bin/bash
# modified <x@xero.nu>

#FULL=▓
#EMPTY=░
FULL=━
EMPTY=━

name=$USER
host=`hostname`
battery=/sys/class/power_supply/BAT0
kernel=`uname -r`
psh=$SHELL

draw() {
perc=$1; size=$2
inc=$(( perc * size / 100 ))
out=
if [ -z $3 ];then color="36"
else color="$3";fi
for v in `seq 0 $(( size - 1 ))`;do
test "$v" -le "$inc" \
&& out="${out}\e[1;${color}m${FULL}" || out="${out}\e[0;${color}m${EMPTY}"
done;printf $out
}
clear && printf "\e[3J\n"

#i=0; while [ $i -le 6 ];do
#printf "\e[$((i+41))m\e[$((i+30))m█▓▒░"
#i=$(($i+1));done
#printf "\e[37m█\e[0m▒\n\n"

printf " \e[0m       hello \e[36m$name\033[0m@\e[34m$host\n\e[0m\n\n"
#printf " \e[1;33m      kernel \e[0m$kernel\n"
#printf " \e[1;33m       shell \e[0m$psh\n"
#printf " \e[0m\n"

cpu=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')
c_lvl=`printf "%.0f" $cpu`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " cpu" "$c_lvl%" `draw $c_lvl 15`

ram=`free | awk '/Mem:/ {print int($3/$2 * 100.0)}'`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " ram" "$ram%" `draw $ram 15`

b_full=$battery/charge_full
b_now=$battery/charge_now
bf=`cat $b_full`
bn=`cat $b_now`
charge=`printf $(( 100 * $bn / $bf ))`

case 1 in
  $(($charge <= 15)))
    color='31'
    ;;
  *)
    color='36'
    ;;
esac
printf "   \e[0;${color}m%-4s \e[1;${color}m%-5s %-25s " " bat" "$charge%" `draw $charge 15 $color`

temp=`sensors | awk '/Core\ 0/ {gsub(/\+/,"",$3); gsub(/\..+/,"",$3)    ; print $3}'`
case 1 in
  $(($temp <= 50)))
    color='34'
    ;;
  $(($temp >= 75)))
    color='31'
    ;;
  *)
    color='36'
    ;;
esac
printf "   \e[0;${color}m%-4s \e[1;${color}m%-5s %-25s \n\n" "temp" "$temp°c " `draw $temp 15 $color`

spc=`du -ch / --exclude=*usr/lib/modules/$kernel/build/include/config/* 2>/dev/null | grep total`
#printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " /" "$spc" `draw $spc 15`
echo $spc

echo -e "\n       ROBCO INDUSTRIES UNIFIED OPERATING SYSTEM \n\
          COPYRIGHT 2075-2077 ROBCO INDUSTRIES \n\
                        -Desktop 1-\n"

