#! /bin/sh

sxhkd &

bspc config border_width         3
bspc config window_gap          20

bspc config normal_border_color         #83a598
bspc config active_border_color         #fabd2f
bspc config focused_border_color        #fabd2f

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer  true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

