#! /bin/sh

sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
conky &

bspc config border_width            1
bspc config window_gap              30

bspc config normal_border_color             
bspc config active_border_color     
bspc config focused_border_color    

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc monitor -d I II III IV V

bspc rule -a Firefox desktop=^2
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating


