#! /bin/sh

sxhkd &
xterm &

bspc config border_width         3
bspc config window_gap          20

bspc config normal_border_color   #628b87        
bspc config active_border_color   #628b87      
bspc config focused_border_color  #1b1b1b      

#fabd2f#83a598

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer  true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors  true

bspc monitor -d I II III IV V

bspc rule -a Screenkey manage=off



