#!/bin/bash

#f=▓;e=░
f=━
e=━

kernel=`uname -r`
bn=`cat /sys/class/power_supply/BAT0/charge_now`
bf=`cat /sys/class/power_supply/BAT0/charge_full`

bar () {
  perc=$1;size=$2
  inc=$(( perc * size / 100 ))
  out=
  for v in `seq 0 $(( size - 1 ))`;do
  test "$v" -le "$inc" && out="${out}\e[1;37m${f}" || out="${out}\e[0;36m${e}"
  done;printf $out
}
clear && printf "\e[3J\n"

cpu=`mpstat -u | awk '/all/' | cut -b 20-24`
c_lvl=`printf "%.0f" $cpu`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " cpu" "$c_lvl%" `bar $c_lvl 15`

ram=`free | awk '/Mem:/ {print int($3/$2 * 100.0)}'`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " ram" "$ram%" `bar $ram 15`

spc=`df -h | awk '/dev\/mmcblk0p2/' | cut -b 35-36`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " /" `bar $spc 15`

chrg=`printf $(( 100 * $bn / $bf ))`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s " " bat" "$chrg%" `bar $chrg 15`

temp=`sensors | awk '/Core\ 0/ {gsub(/\+/,"",$3); gsub(/\..+/,"",$3)    ; print $3}'`
printf "   \e[0;36m%-4s \e[1;36m%-5s %-25s \n" "$temp°c " `bar $temp 15`

echo -e "\n\n      \e[36mROBCO INDUSTRIES UNIFIED OPERATING SYSTEM \n\
        COPYRIGHT 2075-2077 ROBCO INDUSTRIES \n\
                -Server \e[33m$USER\e[0m@\e[34m$HOSTNAME\e[36m-\e[0m\n\n"

