#!/bin/bash

clear && printf "\e[3J"

ered="\e[0;31m"
egrn="\e[0;32m"
eblu="\e[0;34m"
erst="\e[0m"

echo -e "\n\n"
echo -en "          ${ered}█████████${egrn}█████████${eblu}█████████${erst}█████████ \n"
echo -en "          ${ered}█████████${egrn}█████████${eblu}█████████${erst}█████████ \n"
echo -en "          ${ered}█████████${egrn}█████████${eblu}█████████${erst}█████████ \n"
echo -en "          ${ered}█████████${egrn}█████████${eblu}█████████${erst}█████████ \n"
echo -e "\n"

